included:
  - Sources
  - Tests
  - Package.swift
excluded:
  - .build
function_body_length:
  - 500
  - 1000
type_body_length:
  - 1000
  - 2000
file_length:
  warning: 1000
  error: 2000
line_length:
  ignores_urls: true
large_tuple:
  warning: 5
  error: 10
nesting:
  type_level:
    warning: 3
  function_level:
    warning: 3
identifier_name:
  excluded: [
    "^id$",
    "^in$",
    "^bo$",
    "^ad$",
    "^targetedDeviceClassNotSupportedSupplySource$"
  ]
type_name:
  excluded: [
    "^Bo$",
    "^Ad$"
  ]
